NAME = 'team05'
INGESTOR = ''
INSTRUMENT_ID = 'team05'
INSTRUMENT_MFID = '0szb5en16nxdk000dcd8a1wt2w'
UI_MODE = 'standard'
HOLDER_LAYOUTS = {}
DEFAULT_HOLDER_LAYOUT = ''
ACCEPTABLE_FILE_TYPES = {'.bcf', '.bmp', '.csv', '.dm3', '.dm4', '.emd', '.h5', '.jpeg', '.mrc', '.mtd', '.png', '.ser', '.tif', '.txt', '.xls'}
FLOW = None
POST_PROCESSING = []
PANEL_TEMPLATE = None
FILE_PARSER = None
